import type { Editorial, NewsLocale } from "./editorial";
import type { NewsCategory } from "./categories";

// Source-checked editorial batch. Dates are fixed; source datelines are not refresh times.
// Each tuple contains a full edition: headline, deck, reported facts, analysis, next checks.
type Copy = [string,string,string,string,string];
type Story = {slug:string; date:string; category:NewsCategory; source:string; url:string; sourceDate?:string; editions:Record<NewsLocale,Copy>};
const stories:Story[] = [
 {slug:"gold-weekly-close",date:"2026-09-11",category:"prices",source:"The Wall Street Journal · Gold market close",url:"https://www.wsj.com/finance/commodities-futures/gold-rises-ahead-of-u-s-cpi-data-c995e7d0",editions:{
 zh:["黃金期貨週跌1.4%：單日持平，不代表壓力解除","9月11日紐約期金收盤提供一個提醒：日線與週線可能呈現不同訊息，閱讀行情先分清時間尺度。","《華爾街日報》9月11日市場報導指出，紐約近月黃金期貨收在每金衡盎司4,366.20美元，當日變化不大，但一週下跌1.4%。這是歷史期貨收盤紀錄，並非本站即時現貨報價。","一天的平穩收盤，只表示相對前一日的淨變動有限，不能消除前幾個交易日累積的跌幅。對新聞讀者而言，『黃金止穩』與『黃金週線下跌』並不矛盾；兩句話選用的起算點不同。若忽略時間窗口，容易把盤中反彈誤判成整週趨勢扭轉。","接下來比較價格時，應固定同一種商品、合約與收盤時點，再觀察變化是否延續。期貨存在到期與換月因素，不能直接與銀樓每錢售價並列。本文保留消息當時的數字，不將其包裝成週末仍在更新的可成交價；也不由一個收盤點推導下一週漲跌。"],
 en:["Gold futures lose 1.4% for the week despite a steady Friday close","The September 11 New York close illustrates why a quiet session and a weak week can coexist.","The Wall Street Journal reported front-month New York gold futures settling at US$4,366.20 per troy ounce on September 11, little changed that day but down 1.4% for the week. This is a historical futures observation, not a live spot quote.","A stable daily close measures a limited net change from the previous session; it does not erase losses accumulated earlier. Headlines describing stabilization and a weekly decline can therefore both be correct. Their starting points differ. Confusing those windows can turn an intraday recovery into an unjustified claim that a broader trend has reversed.","A useful follow-up keeps the instrument, contract and observation time consistent before asking whether the move persists. Futures expiry and contract rolls also complicate comparisons. A futures settlement should not be placed beside a jewelry dealer’s local-unit selling price as if the products were identical. This article preserves the reported historical number rather than presenting it as an executable weekend price or a forecast for next week."],
 ja:["金先物は週間1.4%安、金曜の横ばいだけでは圧力解消とはいえない","9月11日のニューヨーク終値から、日次と週次の値動きを分けて読む重要性を考えます。","ウォール・ストリート・ジャーナルの9月11日付相場報道によると、ニューヨークの期近金先物は1トロイオンス4,366.20米ドルで終了。当日はほぼ横ばいでしたが、週間では1.4%下落しました。これは過去の先物終値であり、当サイトのリアルタイム現物価格ではありません。","一日の横ばいは前営業日からの純変化が小さいことを示すだけで、それ以前の下落を取り消すものではありません。「下げ止まり」と「週間下落」は、比較の起点が違えば両立します。時間軸を混同すると、取引時間中の反発を中期的な流れの反転と誤解しかねません。","今後は商品、限月、観測時点をそろえて持続性を確認する必要があります。先物には満期や限月交代があり、台湾の貴金属店の売値とは直接比較できません。本記事は報道時点の数字を保存したもので、週末にも更新される約定可能価格ではなく、翌週の騰落を予言するものでもありません。"]}},
 {slug:"gold-etf-august",date:"2026-09-09",category:"supply",source:"World Gold Council · August 2026 ETF flows",url:"https://www.gold.org/goldhub/research/gold-etfs-holdings-and-flows/2026/09",editions:{
 zh:["黃金ETF持有量創高：資金流入與資產增值要分開看","世界黃金協會9月9日發布8月報告，為實物支持型黃金基金的需求提供月度觀察。","世界黃金協會公布，8月全球黃金ETF淨流入約180億美元，持金量增加121噸至4,189噸新高。這份9月9日發布的報告統計的是8月，不能視為9月12日當天的買盤。","閱讀基金規模時，最容易混淆的是『有新資金進來』和『原有黃金變貴』。資產管理規模可能受兩者共同推動，因此判斷配置需求時，應把資金流與實物持有量放在一起，而不是只看美元金額。這份資料的價值，在於呈現基金通道中的持倉變化，不是描繪全球每一種黃金需求。","後續值得追蹤的是流入是否持續，以及下一期資料是否出現相反變化。月度報告具有時間落差，不能用來認定眼前每次反彈都由ETF買盤造成；礦業股基金、期貨型產品與實物支持型基金也應分開。本文是對新公布報告的解讀，不把單月紀錄當成保證上漲的依據。"],
 en:["Gold ETF holdings reach a record: separate inflows from asset appreciation","The World Gold Council’s September 9 release provides a monthly view of demand through physically backed funds.","The World Gold Council reported about US$18 billion of August gold ETF inflows and a 121-tonne increase in holdings to a record 4,189 tonnes. Published September 9, the figures describe August, not buying on September 12.","Fund size can rise because investors add money, because existing gold becomes more valuable, or both. Reading flows alongside physical holdings helps distinguish allocation changes from valuation effects. Dollar assets alone are an incomplete demand signal. These figures describe a particular investment channel rather than every form of global gold consumption.","The next question is whether subsequent data show persistence or reversal. Monthly reporting arrives with a lag and cannot establish that ETF purchases caused each current price bounce. Physically backed funds should also be distinguished from mining-equity funds and futures products. A record month is useful evidence about past positioning, not a guarantee that new buyers will arrive at the same pace or that gold will appreciate."],
 ja:["金ETF保有量が過去最高、資金流入と評価額上昇を区別する","世界黄金協会が9月9日に公表した8月報告は、現物裏付け型ファンドの需要を月次で示します。","世界黄金協会によると、8月の金ETFへの純流入は約180億米ドルで、保有量は121トン増の4,189トンと過去最高になりました。9月9日公表の8月統計であり、9月12日当日の買い需要ではありません。","ファンド規模の拡大には、新しい資金の流入と既存の金の値上がりの両方が影響します。配分需要を考える際はドル建て資産額だけでなく、資金フローと現物保有量を合わせて読むことが重要です。また、これは一つの投資経路の変化であって、世界のあらゆる金需要を表すものではありません。","今後は次回の統計で流入の持続や反転を確認します。月次資料には時間差があるため、現在の反発をすべてETF購入の結果と断定できません。金鉱株ファンド、先物型商品、現物裏付け型商品も区別すべきです。単月の記録は過去の配分を知る材料であり、今後の値上がりを保証しません。"]}},
 {slug:"us-producer-prices",date:"2026-09-10",category:"macro",source:"U.S. Bureau of Labor Statistics · August 2026 PPI",url:"https://www.bls.gov/news.release/archives/ppi_09102026.htm",editions:{
 zh:["美國8月PPI月增0.4%：黃金市場多了一道成本訊號","9月10日公布的生產者物價，呈現供給端價格壓力，解讀時不能直接當成消費者通膨。","美國勞工統計局9月10日公布，8月最終需求生產者物價指數（PPI）季調後月增0.4%、年增5.4%；最終需求商品價格月增1.1%，服務價格月增0.1%。統計對象是生產者端的價格。","這份資料與消費者物價指數回答的問題不同。企業售價變動能否傳到終端消費者，還取決於競爭、庫存、合約與利潤吸收能力。把PPI上升幅度直接加到CPI，或據此宣布下一次利率必然調整，都超出了單份資料能支持的結論。","對黃金的觀察重點，是市場如何重新評估物價壓力的持續性，而非套用『通膨高就買金』。若名目利率與通膨預期同步變動，實質持有成本的方向仍需另外判斷。後續可比較不同物價指標及正式政策聲明；本文不將8月統計當成當日成交價，也不提供據此追單的指令。"],
 en:["US producer prices rise 0.4% in August, adding a cost-pressure signal","The September 10 PPI release describes producer-side pricing, not consumer inflation itself.","The US Bureau of Labor Statistics reported August final-demand PPI rising 0.4% monthly, seasonally adjusted, and 5.4% annually. Final-demand goods increased 1.1% monthly and services 0.1%. The release was published September 10.","Producer and consumer indexes answer different questions. Whether an increase in business selling prices reaches households depends on competition, inventories, contracts and the ability of margins to absorb costs. Adding the PPI increase to CPI, or declaring the next rate decision inevitable, goes beyond what this release establishes.","For gold, the useful question is how expectations about persistent inflation might change, not whether a higher inflation number automatically signals a purchase. If nominal interest rates and inflation expectations move together, the direction of the real opportunity cost still needs separate assessment. Subsequent price indexes and formal policy statements offer additional evidence. August statistics are not current transaction prices, and this analysis supplies no instruction to chase a market move."],
 ja:["米8月PPIは前月比0.4%上昇、金市場に新たなコスト圧力の材料","9月10日公表の生産者物価は供給側の価格を示すもので、消費者物価そのものではありません。","米労働統計局は9月10日、8月の最終需要PPIが季節調整済み前月比で0.4%、前年比で5.4%上昇したと発表しました。最終需要財は前月比1.1%、サービスは0.1%上昇しました。","生産者物価と消費者物価は異なる対象を測っています。企業の販売価格上昇が家計に転嫁されるかは、競争、在庫、契約、利益率による吸収余地などに左右されます。PPIの上昇率をCPIに単純加算したり、次回の金利変更を確定事項としたりすることはできません。","金を見る際は、物価圧力の持続性に対する予想がどう変わるかが焦点です。名目金利とインフレ予想が同時に動くなら、実質的な保有の機会費用も別途検討が必要です。今後の物価統計と公式政策声明を照合することが大切で、本記事は8月統計を当日の取引価格と見なしたり、売買を指示したりするものではありません。"]}},
 {slug:"ecb-rate-increase",date:"2026-09-10",category:"policy",source:"European Central Bank · Monetary policy decisions",url:"https://www.ecb.europa.eu/press/pr/date/2026/html/ecb.mp260910~314e508016.en.html",editions:{
 zh:["歐洲央行再升息一碼：黃金不能只盯聯準會","9月10日的歐洲央行決策，把歐元區利率與匯率因素重新帶入黃金的觀察框架。","歐洲央行9月10日決議將三項主要利率調升25個基點，9月16日生效；存款便利利率將升至2.50%。央行表示不預先承諾特定的後續利率路徑。","黃金雖常以美元報價，持有人卻分布在不同貨幣區。歐元利率變動可能改變當地無息資產的機會成本，也可能透過匯率改變歐元計價金價。因此，即使美元金價沒有變，歐元投資人的報酬感受仍可能不同；不能把單一央行的決策當成全球投資者共同面對的同一個衝擊。","這則消息首先是一項已宣布、尚待生效的政策變動，並不是對下一次會議的承諾。後續閱讀要分清決策日、生效日與市場預期。黃金的實際反應還需要價格資料驗證；本文提出可能的傳導管道，不把升息直接翻譯成金價必跌，也不推算未經核對的交易機率。"],
 en:["ECB raises rates again: gold watchers need more than the Fed","The September 10 decision brings euro-area interest rates and currency effects into focus.","The ECB decided September 10 to raise its three key rates by 25 basis points, effective September 16. The deposit facility rate will reach 2.50%. It did not pre-commit to a particular subsequent rate path.","Gold is often quoted in dollars, but its owners operate in different currency areas. Euro interest rates can change the local opportunity cost of holding a non-yielding asset, while exchange-rate moves can change the euro value of gold. Even an unchanged dollar gold price need not mean an unchanged return for a euro-based holder. One central bank’s decision is not an identical shock for every investor.","This is an announced policy change with a future effective date, not a promise about the following meeting. Decision dates, implementation dates and market expectations should remain distinct. Actual gold-price responses require separate market evidence. These are possible transmission channels, not proof that a rate rise must make gold fall, and no unchecked trading probabilities are inferred here."],
 ja:["ECBが再利上げ、金を見る視点はFRBだけでは足りない","9月10日の決定を受け、ユーロ圏の金利と為替の影響を整理します。","ECBは9月10日、主要3金利を25ベーシスポイント引き上げ、9月16日から適用すると決定しました。預金ファシリティ金利は2.50%になります。今後の特定の金利経路には事前に確約していません。","金はドル建てで表示されることが多い一方、保有者の通貨はさまざまです。ユーロ金利の変化は利息を生まない資産の機会費用を変え、為替を通じてユーロ建て金価格にも影響し得ます。ドル建て価格が同じでも、ユーロで保有する人の損益は同じとは限りません。単一の中央銀行の決定を全投資家共通の影響と捉えるべきではありません。","今回は発表済みで適用前の政策変更であり、次回会合の約束ではありません。決定日、適用日、市場予想を区別する必要があります。実際の金相場への影響は別途価格データで検証すべきです。本記事は考えられる波及経路を整理したもので、利上げなら必ず金が下がると断定するものではありません。"]}},
 {slug:"us-consumer-sentiment",date:"2026-09-11",category:"macro",source:"ABA Banking Journal · Michigan September preliminary survey",url:"https://bankingjournal.aba.com/2026/09/preliminary-consumer-sentiment-decreased-3-9-points-in-september/",editions:{
 zh:["美國消費信心跌至47.8：黃金面對成長與通膨的拉扯","9月11日公布的密西根大學初值，由美國銀行家協會期刊轉述，顯示信心與物價預期走向不同。","美國銀行家協會期刊9月11日引述密西根大學初步調查：9月消費信心指數降至47.8，8月為51.7；一年期通膨預期由4.0%升至4.6%。這是調查初值，而不是實際消費支出或已發生的通膨率。","信心轉弱與通膨預期上升可能同時存在，這也是黃金分析不能只用一個『風險開關』的原因。對成長的疑慮可能提高防禦性配置的討論，但對物價的擔憂也可能使利率預期維持偏高。兩種想法如何反映到金價，取決於市場當時已經消化多少資訊。","後續應對照調查終值與實際支出資料，而不是把受訪者的預期當成未來必然發生的數字。初值可能修訂，調查情緒也不等於所有家庭的購買行為。本篇採用具名二手來源並明列出處；其目的在辨識資料性質與可能影響，不宣称调查已经证明黄金将上涨。"],
 en:["US consumer sentiment falls to 47.8 as inflation expectations rise","A September 11 account of Michigan’s preliminary survey highlights a tension between growth concerns and price expectations.","The ABA Banking Journal cited Michigan’s preliminary September sentiment index at 47.8, down from August’s 51.7. One-year inflation expectations rose from 4.0% to 4.6%. These are survey readings, not measured spending or realized inflation.","Weaker confidence and higher expected inflation can coexist. That is why gold analysis cannot rely on a single risk switch. Concern about growth may encourage discussion of defensive allocations, while concern about prices may sustain expectations of higher rates. How those channels affect gold also depends on how much information markets had already anticipated.","The final survey and actual spending data will provide useful comparisons. Respondents’ expectations should not be treated as numbers that must eventually materialize. Preliminary results can change, and sentiment is not identical to household purchasing behavior. This article identifies its secondary source explicitly. It explains the nature of the evidence and possible implications rather than claiming the survey proves that gold will rise."],
 ja:["米消費者信頼感は47.8に低下、インフレ予想は上昇","9月11日公表のミシガン大学速報値について、米銀行協会の専門誌による報道を整理します。","ABA Banking Journalによると、ミシガン大学の9月消費者信頼感指数速報値は47.8となり、8月の51.7から低下しました。一年先のインフレ予想は4.0%から4.6%へ上昇。実際の消費支出や実現した物価上昇率ではなく、調査による数値です。","景気への自信の低下と物価上昇への懸念は同時に起こり得ます。金を単純なリスクのオン・オフだけで読むことが難しい理由です。成長不安は防御的な配分への関心を高める可能性がある一方、物価不安は高金利予想を支える可能性もあります。金価格への影響は、事前の織り込み具合にも左右されます。","今後は確報値と実際の支出統計を比較します。回答者の予想は将来必ず実現する数字ではなく、速報は修正されることがあります。心理と家計の購買行動も同じではありません。本記事は二次情報源を明示し、資料の性格と考えられる影響を説明するもので、金の上昇を証明するものではありません。"]}},
 {slug:"taiwan-retail-spread",date:"2026-09-12",category:"taiwan",source:"久久銀樓 · 2026-09-12 店家牌價",url:"https://99golden.tw/",editions:{
 zh:["台灣金條買賣價差怎麼看？9月12日店家牌告實例","以一間業者的當日公開牌價為例，分清店家賣出價與收購價，避免把不同產品混在一起比較。","久久銀樓官網9月12日列示，台北9999金條賣出價為每錢新台幣16,850元起，收購價16,400元。這是該店牌價而非全台統一成交價；本文紀錄查閱日期，來源未提供精確到分鐘的更新時刻。","以列示的起價相減，兩者相差450元／錢，約為16,850元的2.67%。這只是同一店家兩個方向的報價比較，不是手續費率，也不是保證買入後立刻可以依該收購價賣回。『賣出』是店家賣給顧客，『收購』才是顧客出售時首先要確認的方向。","比較實體黃金時，還需固定純度、重量單位、品項與報價時間，並詢問檢測及實際成交條件。『元起』也不能省略，因為它不是每件商品的固定總價。本文與該店沒有合作或推薦關係；歷史牌告只作新聞觀察，不代替到店確認，更不能當成本站的即時報價服務。"],
 en:["Reading Taiwan’s gold-bar spread: a September 12 dealer example","A dated retail quote shows why a dealer’s selling and buying prices must be read in the correct direction.","On September 12, Jiujiu’s website listed Taipei 9999 gold bars from NT$16,850 per Taiwan mace for selling and NT$16,400 for buying. This is one dealer’s quote, not a nationwide transaction price; no minute-level update time was supplied.","Subtracting the displayed starting prices gives NT$450 per mace, about 2.67% of NT$16,850. That is a comparison of two quotation directions, not a commission rate or a guarantee of an immediate resale at the quoted bid. Selling means the dealer sells to the customer; buying is the direction relevant when the customer wants to sell gold.","A meaningful physical-gold comparison also fixes purity, weight units, product type and observation time, then checks assessment and transaction conditions. The word ‘from’ matters: it does not specify a fixed total for every item. This article has no promotional relationship with the dealer. Its dated observation does not replace an actual quotation or constitute this site’s live pricing service."],
 ja:["台湾の金地金スプレッドを読む、9月12日の店頭価格例","販売店の売値と買取値の方向を区別し、異なる商品を混ぜて比較しないための事例です。","久久銀樓の9月12日付ウェブ表示では、台北の9999金地金は1台銭あたり販売16,850台湾ドルから、買取16,400台湾ドルでした。一店舗の提示価格で、台湾全体の統一成約価格ではありません。分単位の更新時刻は示されていません。","表示された最低売値と買取値の差は1台銭あたり450台湾ドルで、16,850台湾ドルの約2.67%です。これは売買方向による差であって、手数料率や即時売却価格の保証ではありません。「売出」は店が顧客に売る価格で、顧客が金を売りたい場合は「收購」の方向を確認します。","現物金を比較するには純度、重量単位、品目、時点をそろえ、検査と成約条件も確認する必要があります。「から」という表記を固定の総額と読み替えてはいけません。本記事と当該店舗に提携・推奨関係はありません。日付付きの観測例であり、店舗確認や当サイトのリアルタイム価格サービスに代わるものではありません。"]}},
 {slug:"amex-rose-discovery",date:"2026-09-10",category:"supply",source:"Amex Gold Mining · Rosé discovery announcement",url:"https://amexgoldmining.com/news/2026-news/amex-makes-new-gold-discovery-at-perron-the-ros-zone-app2026-09-10-040503",editions:{
 zh:["Amex發現Rosé金礦化帶：靠近基建，不等於已能開採","Perron計畫9月10日發布新發現，新聞重點是探勘位置與後續驗證，而不是立即增加的黃金產量。","Amex Gold Mining於9月10日宣布，在魁北克Perron計畫發現Rosé礦化帶，位置約在正開發斜坡道下方165公尺。公司列示一段鑽孔結果為4.30公尺、含金8.02克／噸。上述為公司公布的探勘結果。","新礦化帶若靠近既有或規劃中的通道，可能降低未來接近礦體的複雜度，但地理上的接近不能取代經濟評估。鑽孔品位描述的是取樣區間，不代表整個礦床平均品位，更不是已可銷售的金量。從發現到供應市場，仍有連續性、採礦方法、處理流程與資金等問題。","下一步應追蹤更多鑽孔是否支持空間上的延續，以及技術文件如何界定資源。單一亮眼區間不應被放大成整座礦山的產能估算；也不能據此預測全球金價。本篇將公司陳述與本站解讀分開，配圖僅為礦業概念示意，沒有冒充Perron現場或實際鑽芯照片。"],
 en:["Amex identifies Rosé mineralization: proximity is not production","The September 10 Perron discovery is an exploration development, not an immediate addition to gold supply.","Amex Gold Mining announced the Rosé zone at Quebec’s Perron project on September 10, approximately 165 metres below a ramp under development. One reported drill interval was 4.30 metres at 8.02 grams of gold per tonne. These are company-reported exploration results.","Proximity to existing or planned access may simplify a future development route, but geography does not replace economic assessment. A drill grade describes a sampled interval, not the average grade of an entire deposit or a quantity of saleable gold. Continuity, mining methods, processing and funding still stand between a discovery and market supply.","Further holes and technical reporting will help establish whether the mineralization extends consistently and how resources can be defined. A strong interval should not be scaled into a mine-wide production estimate or a prediction of global gold prices. Company statements are separated from our interpretation here. The accompanying mining illustration does not depict Perron or claim to show its actual drill core."],
 ja:["AmexがRosé鉱化帯を発見、インフラに近くても生産確定ではない","9月10日のPerron発表は探鉱上の進展であり、金供給の即時増加ではありません。","Amex Gold Miningは9月10日、ケベック州Perronで、開発中の斜坑道の約165メートル下にRosé鉱化帯を発見したと発表しました。公表された一つの掘削区間は4.30メートル、金品位8.02グラム／トンです。企業による探鉱結果の発表です。","既存または計画中の通路に近いことは、将来の開発を容易にする可能性がありますが、経済性評価の代わりにはなりません。掘削品位は採取区間の値であり、鉱床全体の平均品位や販売可能な金量ではありません。市場供給に至るには連続性、採掘方法、処理工程、資金などの確認が必要です。","今後の追加掘削と技術資料で鉱化の広がりや資源の定義を追うことが重要です。良好な一つの区間から鉱山全体の生産量や世界の金価格を推定すべきではありません。本記事は企業発表と当サイトの解釈を区別しています。配図は鉱業の概念図で、Perronの現場や実際のコア写真ではありません。"]}},
 {slug:"west-red-lake-starratt",date:"2026-09-10",category:"supply",source:"West Red Lake Gold · Starratt-Olsen drilling results",url:"https://westredlakegold.com/west-red-lake-gold-intersects-16-16-g-t-au-over-1-5-metres-and-10-94-g-t-au-over-1-5-metres-at-starratt-olsen-advancing-multi-asset-strategy-at-madsen/",editions:{
 zh:["West Red Lake公布新鑽探結果，Madsen周邊礦源仍待驗證","9月10日Starratt-Olsen公告提供新的局部品位資料，不能把鑽孔長度直接當成礦體厚度。","West Red Lake Gold於9月10日公布Starratt-Olsen首批5孔分析，其中一段為1.5公尺、含金16.16克／噸。公司註明，公告區間是沿鑽孔長度，實際厚度尚未計算。","靠近處理廠的衛星礦源，理論上可共享部分設施，但是否能轉化成有效供料，仍須看礦體形狀、採掘成本與處理相容性。高品位區間能提供後續勘探線索，卻不能單靠品位與长度就推算可採噸數。尤其鑽孔若斜穿礦體，沿孔距離與真正厚度不同。","後續要檢查剩餘鑽孔、礦化連續性及技術研究如何處理這些差異，再判斷是否存在可經濟開發的增量礦源。這則新聞是探勘資料更新，不是宣布新增商業產量；本站不把企業目標寫成已實現成果，也不以單一區間替礦業股設定目標價。"],
 en:["West Red Lake reports new drilling as the Madsen feed pipeline is tested","The September 10 Starratt-Olsen release adds local assay evidence, not a confirmed increase in commercial output.","West Red Lake Gold reported results from five Starratt-Olsen holes on September 10, including 1.5 metres at 16.16 grams of gold per tonne. It identified the intervals as downhole lengths and said true thickness had not been calculated.","Satellite deposits near a processing plant may share infrastructure, but usable feed still depends on geometry, mining costs and processing compatibility. High-grade intervals can guide further exploration; grade and length alone cannot establish mineable tonnage. A hole intersecting mineralization at an angle may record a longer interval than the actual thickness of the zone.","Remaining holes, continuity and technical studies should clarify those distinctions before an economically developable addition can be assessed. This is an update to exploration evidence, not an announcement of new commercial production. Corporate ambitions are not treated as achieved outcomes, and a single intercept supplies no basis here for a mining-equity price target."],
 ja:["West Red Lakeが新たな掘削結果、Madsen周辺の鉱源候補を検証","9月10日のStarratt-Olsen発表は局所的な分析結果であり、商業生産の増加を確定するものではありません。","West Red Lake Goldは9月10日、Starratt-Olsenの5孔の結果を公表し、1.5メートルで金16.16グラム／トンの区間を報告しました。区間は孔に沿った長さで、真の厚さは未計算と明記しています。","処理施設に近い衛星鉱床はインフラを共有できる可能性がありますが、供給可能な鉱石になるかは形状、採掘費、処理適合性などに左右されます。高品位区間は追加探鉱の手掛かりにはなっても、品位と長さだけで可採鉱量を求めることはできません。斜めに鉱体を通る孔では、区間長が実際の厚さより長くなる場合があります。","残りの孔、鉱化の連続性、技術調査でこれらの違いを確認し、経済的に開発できる追加鉱源かを評価する必要があります。今回は探鉱データの更新であり、新たな商業生産の発表ではありません。企業の目標を実績として扱わず、単一区間から株価目標も設定しません。"]}},
 {slug:"don-david-operations",date:"2026-09-10",category:"supply",source:"Goldgroup Mining · Don David operating overview",url:"https://www.goldgroupmining.com/news/goldgroup-highlights-its-two-producing-mines-and-significant-growth-2026-09-10-doc-120414",editions:{
 zh:["Goldgroup更新Don David營運：兩座在產礦山與探勘並行","9月10日營運概覽，把現有生產與未來礦源的工作分開，不能將鑽探規模當成產量。","Goldgroup於9月10日介紹墨西哥Don David礦區：Arista與Alta Gracia兩座地下礦山正在生產，2026年34,250公尺鑽探計畫進行中。這是公司營運概覽，不代表當天新增兩座礦山。","在產企業與純探勘企業的觀察重點不同。前者需要持續補充礦源，也必須維持現有採礦與處理活動。鑽探公尺數衡量的是工作規模，並不是發現多少黃金，更不能直接換算未來收入。礦區範圍與已知礦脈提供機會，但真正的產出還要通過開採、回收與銷售環節。","接下來較有判讀價值的是公司披露的實際處理量、品位、回收率與成本是否互相支持，再看探勘能否補強礦山壽命。單篇營運概覽不等於新的財務指引。本文保留公告本身的性質，不把『在產』錯寫成『今天投產』，也不把公司對成長的期待當成供應量已經增加。"],
 en:["Goldgroup reviews Don David: operating mines and exploration run together","The September 10 overview separates existing production from work on future mineral sources.","Goldgroup’s September 10 Don David overview identified Arista and Alta Gracia as producing underground mines and a 34,250-metre 2026 drilling program as underway. It was an operating review, not the opening of two new mines that day.","An operating miner and a pure explorer require different questions. The producer must replenish its mineral pipeline while sustaining current extraction and processing. Drill metres measure the scale of work, not gold discovered or future revenue. A land package and known veins offer opportunities, but material still has to pass through mining, recovery and sale to become output.","Subsequent throughput, grade, recovery and cost disclosures should be examined together, followed by evidence that exploration can support mine life. An operational overview is not automatically new financial guidance. This article preserves that distinction: producing does not mean newly commissioned, and management’s growth ambitions are not counted as gold already added to market supply."],
 ja:["GoldgroupがDon David操業を更新、生産と探鉱を並行","9月10日の概況は既存生産と将来の鉱源確保を示し、掘削距離を生産量と混同しないことが重要です。","Goldgroupは9月10日のDon David概況で、AristaとAlta Graciaを稼働中の地下鉱山として紹介し、2026年の34,250メートル掘削計画が進行中と説明しました。当日に新しく二鉱山が開業したという発表ではありません。","生産企業と探鉱専業企業では、確認する点が異なります。前者は現在の採掘・処理を維持しつつ鉱源を補充する必要があります。掘削距離は作業規模であり、発見金量や将来売上高ではありません。土地や既知の鉱脈が機会を与えても、産出には採掘、回収、販売が必要です。","今後は処理量、品位、回収率、コストを一緒に確認し、探鉱が鉱山寿命の維持につながるかを見ることが有用です。操業概況は自動的に新たな業績予想を意味しません。本記事は「稼働中」を「本日生産開始」と書き換えず、経営側の成長期待を実現済み供給として扱いません。"]}},
 {slug:"goldgroup-financing",date:"2026-09-08",sourceDate:"2026-09-09",category:"supply",source:"Goldgroup Mining · Private placement announcement",url:"https://www.goldgroupmining.com/news/goldgroup-announces-us-75-million-private-placement-with-us-2026-09-09-qm-6203992764191703",editions:{
 zh:["Goldgroup擬募資7,500萬美元：認購承諾不等於資金入帳","公司募資公告與礦区营运更新是不同事件；閱讀融資新聞，先辨認宣布、承諾與完成三個階段。","Goldgroup公告擬私募約7,500萬美元，約6,000萬美元已獲承諾，仍待核准與交割。官網頁面日期為9月9日，但內文公告日期為9月8日；本文以較早的內文日期記錄事件，不宣稱募集已完成。","融資消息對礦業的重要性，在於可用資金與後續資本支出的配合，而不是標題金額本身。投資人承諾、正式交割及公司可動用的淨額並不相同。新股發行也可能改變既有股東的持分，因此『取得成長資金』與『每股價值提升』不能畫上等號。","後續應看交割公告、最終規模、發行條件與資金用途是否落實，再對照项目进度。募資能增加選擇，不能保證勘探成功、建設如期或金價配合。本篇與該公司的礦區營運新聞分開編列，因為一篇是資本安排、一篇是生產概覽；兩者不互相證明成果已實現。"],
 en:["Goldgroup proposes US$75 million financing: commitments are not cash received","Funding and operating updates are different events; announcement, commitment and completion should not be confused.","Goldgroup proposed about US$75 million of private-placement financing, with roughly US$60 million committed, subject to approvals and closing. The page is dated September 9 but its release dateline is September 8; this article uses the earlier event date and does not claim completion.","Mining finance matters through the relationship between available capital and future spending, not merely the headline amount. Investor commitments, formal closing and usable net proceeds are different stages. Issuing shares can also change existing holders’ ownership, so obtaining growth funding does not automatically mean increasing value per share.","A closing announcement, final size, issuance terms and implemented use of proceeds should be compared with project progress. Financing increases options; it does not guarantee exploration success, timely construction or supportive gold prices. This story is separate from the company’s operational review because capital arrangements and current mine activity are distinct developments. Neither is proof that the other has already delivered its intended results."],
 ja:["Goldgroupが7,500万米ドル調達を計画、引受約束と入金は別","資金調達と操業更新は別の出来事です。発表、コミットメント、完了を区別して読みます。","Goldgroupは約7,500万米ドルの私募を計画し、約6,000万米ドルのコミットメントを得たと発表しましたが、承認と取引完了が必要です。ページ日付は9月9日、本文発表日は9月8日のため、本記事は早い方を出来事の日付とし、完了とは記していません。","鉱業の資金調達は、見出しの金額だけでなく、利用可能資金と今後の支出の関係が重要です。引受約束、正式な取引完了、利用可能な純手取額は別段階です。新株発行は既存株主の持分にも影響し得るため、成長資金の確保が一株価値の向上を自動的に意味するわけではありません。","今後は完了発表、最終規模、発行条件、資金使途を計画の進捗と照合する必要があります。調達は選択肢を増やしても、探鉱成功や工事予定、金相場を保証しません。本記事は資本面の出来事として操業概況と分けています。どちらかの発表だけで、もう一方の狙いが実現したとは判断できません。"]}},
];

const headings = {zh:["新聞事實","本站解讀","後續觀察"],en:["Reported facts","Our analysis","What to watch"],ja:["報道・発表の事実","当サイトの分析","今後の確認点"]};
const alts = {
 market:{zh:"金條、透明建築柱與玻璃球的AI市場概念示意圖",en:"AI concept illustration of gold bars, translucent columns and a glass sphere",ja:"金の延べ棒、透明な柱と球体を配置したAI市場イメージ"},
 mining:{zh:"鑽芯樣本、金條與遠方礦區輪廓的AI礦業示意圖",en:"AI mining illustration with drill cores, a gold bar and a distant mine silhouette",ja:"コア試料、金地金、遠景の鉱山を表現したAI鉱業イメージ"},
 retail:{zh:"金飾、金條與珠寶秤的AI零售黃金示意圖",en:"AI retail-gold illustration of jewelry, a gold bar and a weighing scale",ja:"金の装飾品、地金と秤を表現したAI小売イメージ"},
};
// Remaining drafts are intentionally unpublished: outside this run's 24-hour window.
const approved = new Set(["gold-weekly-close", "taiwan-retail-spread"]);
export const batchSeptember12:Editorial[] = stories.filter(s=>approved.has(s.slug)).flatMap(s=>(["zh","en","ja"] as NewsLocale[]).map(locale=>{
 const [title,description,facts,analysis,watch]=s.editions[locale];
 const art=s.category==="taiwan"?"retail":s.category==="supply"&&s.slug!=="gold-etf-august"?"mining":"market";
 const group=s.slug+"-20260912";
 return {id:group+"-"+locale,group,locale,title,description,category:s.category,eventDate:s.date,publishedAt:"2026-09-12T14:30:09Z",image:`/news-${art}-20260912.webp`,imageAlt:alts[art][locale],sources:[{title:s.source,url:s.url,date:s.sourceDate??s.date}],sections:[{heading:headings[locale][0],paragraphs:[facts],source:0},{heading:headings[locale][1],paragraphs:[analysis]},{heading:headings[locale][2],paragraphs:[watch]}]};
}));
