"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import "./global.css";

type Metal = { id: string; symbol: string; name: string; englishName: string; price: number; changePercent: number | null };
type Data = { metals: Metal[]; currencies: Record<string, number>; updatedAt: string; source: string };
const fallback: Data = {metals:[],currencies:{},updatedAt:"",source:""};
const markets = [
  ["台灣", "Taipei", "TWD／錢、公克", "09:00–17:00"], ["香港", "Hong Kong", "HKD／兩、克", "09:00–17:00"], ["中國", "Shanghai", "CNY／克", "09:00–15:30"], ["日本", "Tokyo", "JPY／克", "09:00–15:30"], ["新加坡", "Singapore", "SGD／盎司", "09:00–17:00"], ["倫敦", "London", "USD／盎司", "08:00–17:00"], ["紐約", "New York", "USD／盎司", "08:20–17:00"],
];

export default function GlobalMarketPage() {
  const [data, setData] = useState(fallback); const [metalId, setMetalId] = useState("gold"); const [currency, setCurrency] = useState("TWD"); const [weight, setWeight] = useState("1"); const [unit, setUnit] = useState("ounce");
  useEffect(() => { fetch("/api/global-quotes", { cache: "no-store" }).then((r) => r.ok ? r.json() : null).then((d) => d && setData(d)).catch(() => undefined); }, []);
  const metal = data.metals.find((item) => item.id === metalId) ?? data.metals[0];
  const result = useMemo(() => { const ounces = (Number(weight) || 0) * ({ ounce: 1, gram: 1 / 31.1034768, qian: 3.75 / 31.1034768, tael: 37.5 / 31.1034768 }[unit] ?? 1); return ounces * (metal?.price ?? Number.NaN) * (data.currencies[currency] ?? Number.NaN); }, [weight, unit, metal, currency, data]);
  return <main className="globalPage"><header className="globalNav"><Link href="/"><b>99</b><span>玖久黃金報價網<small>99GOLD.NET</small></span></Link><nav><Link href="/">首頁</Link><Link className="active" href="/global">全球報價</Link><Link href="/insights">市場情報</Link></nav></header><section className="globalHero"><p>GLOBAL PRECIOUS METALS</p><h1>全球貴金屬報價中心</h1><span>{data.source || "正在連接可驗證的國際行情來源"}；屬參考資訊，並非店家可成交牌告</span></section><section className="metalBoard"><div className="boardHead"><div><p>LIVE PRICES</p><h2>國際市場參考行情</h2></div><time>{data.updatedAt ? new Date(data.updatedAt).toLocaleString("zh-TW") : "沒有有效報價，請稍後再試"}</time></div><div className="metalGrid">{data.metals.map((item) => { const hasChange = item.changePercent !== null && Number.isFinite(item.changePercent); return <button key={item.id} className={metalId === item.id ? "selected" : ""} onClick={() => setMetalId(item.id)}><span>{item.englishName}</span><h3>{item.name}</h3><strong>US$ {item.price.toLocaleString("en-US", { maximumFractionDigits: 2 })}</strong><em className={hasChange ? item.changePercent! >= 0 ? "rise" : "fall" : undefined}>{hasChange ? `${item.changePercent! >= 0 ? "+" : ""}${item.changePercent!.toFixed(2)}%` : "有效參考價"}</em><small>每金衡盎司</small></button>; })}</div></section><section className="converter"><div><p>CURRENCY CONVERTER</p><h2>貴金屬幣別換算</h2><span>依有效國際參考報價與匯率估算</span></div><form><label>金屬<select value={metalId} onChange={(e) => setMetalId(e.target.value)}>{data.metals.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>重量<div className="pair"><input type="number" min="0" step="0.01" value={weight} onChange={(e) => setWeight(e.target.value)}/><select value={unit} onChange={(e) => setUnit(e.target.value)}><option value="ounce">盎司</option><option value="gram">公克</option><option value="qian">錢</option><option value="tael">台兩</option></select></div></label><label>幣別<select value={currency} onChange={(e) => setCurrency(e.target.value)}>{Object.keys(data.currencies).map((code) => <option key={code}>{code}</option>)}</select></label></form><div className="convertResult"><span>換算結果</span><strong>{currency} {Number.isFinite(result) ? result.toLocaleString("en-US", { maximumFractionDigits: 2 }) : "—"}</strong><small>{weight || 0} {unit}・{metal?.name ?? "資料不可用"}</small></div></section><section className="worldMarkets"><div className="boardHead"><div><p>WORLD MARKETS</p><h2>主要黃金市場</h2></div><span>當地交易單位與市場時間</span></div><div>{markets.map(([name, city, unitLabel, hours]) => <article key={name}><span>{city}</span><h3>{name}</h3><p>{unitLabel}</p><strong>{hours}</strong><small>當地市場時間</small></article>)}</div></section><footer><span>玖久黃金報價網 · 99GOLD.NET</span><p>真金價值，長久相伴。</p></footer></main>;
}
